language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
  - phpunit

notifications:
  slack: mercari:maGUctUC7sBBb3XjXeUxAfHE

matrix:
  allow_failures:
    - php: hhvm
