language: php

sudo: false

php:
  - 5.6

before_script:
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
  - phpunit

notifications:
  slack: mercari:oyDHhpauwDLXPvDsFVGaMOCg
